import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material 3 grayscale palette (from reference designs)
        primary: "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "primary-fixed-dim": "#c6c6c6",
        secondary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e1dfdf",
        "on-secondary-container": "#626262",
        "secondary-fixed": "#e4e2e2",
        "on-secondary-fixed": "#1b1c1c",
        "on-secondary-fixed-variant": "#464747",
        "secondary-fixed-dim": "#c7c6c6",
        tertiary: "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#1a1c1c",
        "on-tertiary-container": "#838484",
        "tertiary-fixed": "#e3e2e2",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "tertiary-fixed-dim": "#c7c6c6",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        surface: "#f9f9f9",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#4c4546",
        "surface-dim": "#dadada",
        "surface-bright": "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "surface-subtle": "#FBFBFB",
        "surface-pure": "#FFFFFF",
        "surface-tint": "#5e5e5e",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        outline: "#7e7576",
        "outline-variant": "#cfc4c5",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f1f1f1",
        "inverse-primary": "#c6c6c6",
        "border-light": "#E5E5E5",
        "border-bold": "#000000",
        // Functional status colors (kept for StatusBadge)
        success: { light: "#dcfce7", DEFAULT: "#16a34a", text: "#15803d" },
        danger: { light: "#fee2e2", DEFAULT: "#dc2626", text: "#b91c1c" },
        warning: { light: "#fef3c7", DEFAULT: "#d97706", text: "#b45309" },
        info: { light: "#dbeafe", DEFAULT: "#2563eb", text: "#1d4ed8" },
      },
      fontFamily: {
        sans: ["Work Sans", "system-ui", "-apple-system", "sans-serif"],
        headline: ["Manrope", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        "margin-mobile": "16px",
        gutter: "24px",
        "margin-desktop": "40px",
        base: "8px",
        "section-gap": "48px",
        "stack-sm": "12px",
        "container-padding": "32px",
        "stack-md": "20px",
        sidebar: "280px",
      },
      width: {
        sidebar: "280px",
      },
      height: {
        topbar: "64px",
      },
      boxShadow: {
        ambient: "0px 4px 20px rgba(45, 62, 78, 0.05)",
        "ambient-hover": "0px 8px 24px rgba(45, 62, 78, 0.08)",
      },
    },
  },
  plugins: [],
};

export default config;
